---
title: "RWeekly Curation Calendar"
format: 
  dashboard: 
    logo: "assets/icon-256x256.png"

execute: 
  echo: false
---


```{r}
#| label: setup
#| include: false
library(dplyr)
library(toastui)
library(reactable)
library(htmltools)

# load supporting functions
source("R/create_curator_df.R")
source("R/import_schedule_functions.R")
source("R/process_cal_data.R")
source("R/curator_table.R")
```

```{css}
.imageclass {
  height: 1.3rem;
}

.profile-pic {
    width: 50px;
    height: 50px;
    border-radius: 50%;
    object-fit: cover;
}
```

# Schedule

```{r}
# import schedule data from public API endpoint
raw_schedule_df <- import_schedule_data()

# import curator data from public API endpoint
raw_curator_df <- import_curator_data()

# derive a processed data set for use with calendar
processed_cal_data <- process_cal_data(raw_schedule_df, raw_curator_df)
```

## Row {height=60%}

```{r}
toastui::calendar(
  data = processed_cal_data,
  view = "month",
  navigation = TRUE,
  useDetailPopup = FALSE,
  useCreationPopup = FALSE
) |>
  toastui::cal_month_options(
    startDayOfWeek = 1,
    narrowWeekend = FALSE
  )
```

## Row {height="40%"}

```{r}
create_schedule_table(raw_schedule_df, raw_curator_df)
```